### ISSUE TITLE
Add Media Section

### ISSUE THREAD

**Issue by sam17** [quadrotor-IITKgp/quadrotor-IITKgp.github.io#49]
Add media section with links to the articles using logos of the media houses.
- http://timesofindia.indiatimes.com/city/kolkata/IIT-Kharagpur-students-developing-fully-indigenous-drones/articleshow/54897093.cms
- http://economictimes.indiatimes.com/news/science/iit-kharagpur-students-developing-fully-indigenous-drones/articleshow/54896790.cms
- http://indianexpress.com/article/technology/gadgets/iit-kharagpur-students-developing-fully-indigenous-drones-3087564/
- http://www.business-standard.com/article/current-affairs/make-in-india-iit-kharagpur-students-developing-fully-indigenous-drones-116101700466_1.html
- http://www.daijiworld.com/news/news_disp.asp?n_id=419125
- http://www.nayaindia.com/technology/iit-kharagpur-student-ark-sric-indigenous-drone-develop-570851.html

**Comment by shivangag** [comment]
@sam17 Don't you think our landing page is cluttered way too much to add a new section?

**Comment by sam17** [comment]
Yes, hence we need to change design but first let's just dump all the content in an acceptable way and then change design.

**Comment by shivangag** [comment]
Peace. I'll add the section today.
